version: 2.1
description: "Tools for running test commands."

jobs:
  pipcheck:
    description: |
      Runs pip check against the current repo.
    docker:
      - image: python:<<parameters.python_version>>
    resource_class: <<parameters.resource_class>>
    parameters:
      cache_prefix:
        default: ''
        description: >
          Optional cache prefix to be used on CircleCI. Can be used for cache
          busting or to ensure multiple jobs use different caches.
        type: string
      cwd:
        default: '.'
        description: >
          Working directory used when running pip / pytest commands.
        type: string
      enable_caching:
        default: true
        description: |
          Whether the CircleCI cache should be used for pip dependencies.
        type: boolean
      install_args:
        default: pytest
        description: |
          Arguments to `pip install` command.
        type: string
      python_version:
        default: 3.7.8
        description: |
          The python version used to run pytest.
        type: string
      resource_class:
        default: small
        type: string
    steps:
      - checkout
      - when:
          condition: <<parameters.enable_caching>>
          steps:
            - restore_cache:
                keys:
                  - cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-{{ .Branch }}-{{ .Revision }}
                  - cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-{{ .Branch }}-
                  - cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-
      - run:
          name: python -m pip install --progress-bar=off <<parameters.install_args>>
          command: |
            cd <<parameters.cwd>>
            python -m pip install --progress-bar=off <<parameters.install_args>>
      - when:
          condition: <<parameters.enable_caching>>
          steps:
            - save_cache:
                key: cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-{{ .Branch }}-{{ .Revision }}
                paths:
                  - ~/.cache/pip
      - run:
          name: python -m pip check
          command: |
            cd <<parameters.cwd>>
            python -m pip check

  pytest:
    description: |
      Runs pytest against the current repo.
    docker:
      - image: python:<<parameters.python_version>>
    resource_class: <<parameters.resource_class>>
    parameters:
      args:
        default: ''
        description: |
          Arguments to pass to pytest.
        type: string
      cache_prefix:
        default: ''
        description: >
          Optional cache prefix to be used on CircleCI. Can be used for cache
          busting or to ensure multiple jobs use different caches.
        type: string
      cwd:
        default: '.'
        description: >
          Working directory used when running pip / pytest commands.
        type: string
      enable_caching:
        default: true
        description: |
          Whether the CircleCI cache should be used for pip dependencies.
        type: boolean
      install_args:
        default: pytest
        description: |
          Arguments to `pip install` command.
        type: string
      python_version:
        default: 3.7.8
        description: |
          The python version used to run pytest.
        type: string
      resource_class:
        default: small
        type: string
    steps:
      - checkout
      - when:
          condition: <<parameters.enable_caching>>
          steps:
            - restore_cache:
                keys:
                  - cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-{{ .Branch }}-{{ .Revision }}
                  - cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-{{ .Branch }}-
                  - cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-
      - run:
          name: python -m pip install --progress-bar=off <<parameters.install_args>>
          command: |
            cd <<parameters.cwd>>
            python -m pip install --progress-bar=off <<parameters.install_args>>
      - when:
          condition: <<parameters.enable_caching>>
          steps:
            - save_cache:
                key: cache-pip-<<parameters.python_version>>-<<parameters.cache_prefix>>-{{ .Branch }}-{{ .Revision }}
                paths:
                  - ~/.cache/pip
      - run:
          name: python -m pytest <<parameters.args>>
          command: |
            cd <<parameters.cwd>>
            python -m pytest <<parameters.args>>

  docker-compose:
    description:
      Runs docker-compose service
    docker:
      - image: <<parameters.executor>>
        user: <<parameters.user>>
    resource_class: <<parameters.resource_class>>
    parameters:
      args:
        default: ''
        description: |
          Arguments to pass to downstream container
        type: string
      build:
        default: ''
        description: |
          Services to build besides target service
        type: string
      cwd:
        default: '.'
        description: >
          Working directory used when running docker-compose commands.
        type: string
      compose_args:
        default: '-f docker-compose.yaml'
        description: >
          Docker-compose args such as a chain of files to use.
        type: string
      gcr_creds:
        default: GCLOUD_SERVICE_KEY
        description: >
          Name of environment variable storing the base64-encoded service key
          for the GCP project.
        type: env_var_name
      executor:
        default: cimg/base:2020.01
        description: >
          Name of the docker image to use to execute the job.
        type: string
      user:
        # this parameter exists because base executor image defaults to non-root user
        default: root
        description: >
          Which system user executor should run.
        type: string
      gcr_project:
        default: ""
        description: >
          Name of GCP project to pull images from.
        type: string
      resource_class:
        default: small
        type: string
      service_name:
        description: >
          Name of docker-compose service to run
        type: string
    steps:
      - when:
          condition:
            and: [<<parameters.gcr_creds>>, <<parameters.gcr_project>>]
          steps:
            - gcloud/install
            - gcloud/auth:
                creds: <<parameters.gcr_creds>>
                project: <<parameters.gcr_project>>
            - gcloud/configure-docker
      - unless:
          condition:
            and: [<<parameters.gcr_creds>>, <<parameters.gcr_project>>]
          steps:
            - setup_remote_docker:
                version: 18.09.3
      - checkout
      - run:
          working_directory: <<parameters.cwd>>
          # has to be built explicitly https://github.com/docker/compose/issues/7336
          command: docker-compose <<parameters.compose_args>> build <<parameters.service_name>> <<parameters.build>>
          environment:
            DOCKER_BUILDKIT: 1
            COMPOSE_DOCKER_CLI_BUILD: 1
      - run:
          working_directory: <<parameters.cwd>>
          command: docker-compose <<parameters.compose_args>> run --rm <<parameters.service_name>> <<parameters.args>>
          environment:
            # Workaround for docker-compose being unable to pull image from gcr
            # https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/193#issuecomment-586288752
            LD_LIBRARY_PATH: /usr/local/lib
      - run:
          working_directory: <<parameters.cwd>>
          command: docker-compose <<parameters.compose_args>> logs -t | sort -u -k 3
          when: on_fail

orbs:
  gcloud: talkiq/gcloud@4
