version: 2.1
description: "Tools for running poetry commands."

jobs:
  run:
    description: >
      Run an arbitrary command within your poetry environment.
    docker:
      - image: python:<<parameters.python_version>>
    resource_class: <<parameters.resource_class>>
    parameters:
      cmd:
        type: string
      cwd:
        default: '.'
        description: >
          Working directory for your package. Should point to a folder
          containing your pyproject.toml file.
        type: string
      python_version:
        default: latest
        type: string
      poetry_http_basic_configurations:
        default: ''
        description: >
          A semicolon separated list of triplets used to configure
          poetry's HTTP basic authentication. Order is as follows:

          repository_name[,] username[,] password[;]

          Spaces are required between values. Commas and semicolons
          are to improve triplet readability.
        type: string
      resource_class:
        default: small
        type: string
    steps:
      - run: python3 -m pip install poetry
      - run: echo "<<parameters.poetry_http_basic_configurations>>" | xargs -r -n 3 bash -c 'poetry config http-basic.${0%,*} ${1%,*} ${2%;*}'
      - checkout
      - run:
          command: poetry install -n --no-ansi
          working_directory: <<parameters.cwd>>
      - run:
          command: poetry run <<parameters.cmd>>
          working_directory: <<parameters.cwd>>

  publish:
    description: >
      Publishes your package to the specified repository.
    docker:
      - image: python:<<parameters.python_version>>
    resource_class: <<parameters.resource_class>>
    parameters:
      cwd:
        default: '.'
        description: >
          Working directory for your package. Should point to a folder
          containing your pyproject.toml file.
        type: string
      python_version:
        default: latest
        type: string
      resource_class:
        default: small
        type: string
      password:
        description: >
          Password to be used for authenticating against the specified
          repository. Note that some indexes such as Gemfury use the username
          field for your personal access token; in that case, set this value to
          the same value as the username.
        type: string
      repository:
        default: pypi
        description: >
          Name of the repository you wish to upload to. If using a non-default
          repository, you'll need to define it in your pyproject.toml or
          provide a URL with the repository_url parameters.
        type: string
      repository_url:
        default: ''
        description: >
          URL of repository not provided in pyproject.toml. Uses repository
          parameter as name of repository for configuration.
        type: string
      username:
        description: >
          Username to be used for authenticating against the specified
          repository.
        type: string
    steps:
      - run: python3 -m pip install poetry
      - checkout
      - run:
          name: validate tag matches pyproject.toml
          command:
            if [[ "${CIRCLE_TAG}" != *"$(poetry version | cut -d ' ' -f2)"* ]]; then
                echo "Version $(poetry version) does not match tag ${CIRCLE_TAG}";
                exit 1;
            fi
          working_directory: <<parameters.cwd>>
      - run:
          command: poetry build
          working_directory: <<parameters.cwd>>
      - when:
          condition: << parameters.repository_url >>
          steps:
            - run: poetry config repositories.<<parameters.repository>> <<parameters.repository_url>>
      - run:
          name: poetry publish
          command: poetry publish -r <<parameters.repository>> -u <<parameters.username>> -p <<parameters.password>>
          working_directory: <<parameters.cwd>>
