version: 2.1
description: "Tools for running deployment commands"

jobs:
  docs:
    description: >
      Deploy a package's Sphinxdocs to Google Storage (ie. for internal use
      only). Deprecated: use the `talkiq/docs` orb.
    docker:
      - image: python:3.7.6-alpine
    parameters:
      creds:
        default: GCLOUD_SERVICE_KEY
        description: >
          Name of environment variable storing the base64-encoded service key
          for the GCP project.
        type: env_var_name
      folder:
        default: '.'
        description: >
          Path to the folder containing the Python package.
        type: string
      gcp_project:
        description: The Google project ID to connect with via the gcloud CLI.
        type: string
      project:
        default: ${CIRCLE_PROJECT_REPONAME}
        description: |
          The name of the project.
        type: string
    steps:
      - gcloud/install
      - gcloud/auth:
          creds: <<parameters.creds>>
          project: <<parameters.gcp_project>>
      - run: python3 -m pip install sphinx
      - checkout
      - run: sphinx-apidoc -M -e -f -o ./docs/code/ <<parameters.folder>>/
      - run:
          name: clean up sphinx-apidoc cruft
          command: |
            rm -f ./docs/code/modules.rst ./docs/code/voiceai.rst
      - run: sphinx-build -M html ./ build/
      - run:
          name: nuke pre-existing docs
          command: |
            gsutil -m rm -r gs://<<parameters.gcp_project>>-docs/<<parameters.project>>/ ||:
      - run: gsutil -m cp -r build/html/* gs://<<parameters.gcp_project>>-docs/<<parameters.project>>/

  gemfury:
    description: >
      Deploy a package to Gemfury (ie. for internal usage only). Use PyPI for
      OSS projects!
    docker:
      - image: python:<<parameters.python_version>>
    resource_class: <<parameters.resource_class>>
    parameters:
      folder:
        default: '.'
        description: >
          Path to the folder containing the Python package.
        type: string
      gemfury_token:
        default: GEMFURY_TOKEN
        description: >
          Name of the env var containing the Gemfury token.
        type: env_var_name
      python_version:
        description: >
          Python version to use to build and deploy the package. Used as the
          docker executor, so you can use any sort of tag (eg. ``3.7.4-slim``).
        type: string
      resource_class:
        default: small
        type: string
      verify_version:
        default: ${CIRCLE_TAG}
        description: >
          If set to a non-empty value, fails the deployment if the version
          being deployed does not match. Can be used as a last-step sanity
          check.
        type: string
    steps:
      - checkout
      - run: python3 -m pip install wheel
      - run: cd "<<parameters.folder>>" && python3 setup.py sdist bdist_wheel
      - run:
          name: verify tag builds match deploy version
          command: |
            if [[ ! -z "<<parameters.verify_version>>" ]]; then
                code_version=$(find "<<parameters.folder>>/dist" -iname '*.tar.gz' | awk -F- '{sub(/\.tar\.gz/, ""); print $NF}')
                code_version_alt="${code_version/.dev/-dev.}"
                if [[ <<parameters.verify_version>> != ${code_version} &&
                      <<parameters.verify_version>> != ${code_version_alt} ]]; then
                    echo "Version ${code_version} does not match tag ${CIRCLE_TAG}"
                    exit 1
                fi
            fi
      - run: ls "<<parameters.folder>>/dist" | xargs -I{} curl -F package=@<<parameters.folder>>/dist/{} https://${<<parameters.gemfury_token>>}@push.fury.io/talkiq/

orbs:
  gcloud: talkiq/gcloud@1
